FROM docker.elastic.co/elasticsearch/elasticsearch:9.0.0

USER root
COPY certs /usr/share/elasticsearch/config/certs
RUN chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/config/certs \
 && chmod -R 750 /usr/share/elasticsearch/config/certs
USER elasticsearch
